apiVersion: apps/v1
kind: Deployment
metadata:
  name: cron-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cron-app
  template:
    metadata:
      labels:
        app: cron-app
    spec:
      securityContext:
        runAsUser: 1000  # Assuming 1000 is the non-root user ID
      containers:
        - name: cron-container
          image: prashant2020/tomcatsampleapp
          securityContext:
            readOnlyRootFilesystem: true  # Enable read-only root filesystem
          volumeMounts:
            # Mount for Tomcat writable directory
            - name: tomcat-workdir
              mountPath: /opt/tomcat/work
            - name: tomcat-dir
              mountPath: /opt/tomcat/logs
            # Mount for cron jobs writable directory (e.g., for logs)
            - name: cron-output
              mountPath: /tmp/cron_output
            # Mount for cron job scripts directory
            - name: cronjobs
              mountPath: /tmp/cronjobs
      volumes:
        - name: tomcat-workdir
          emptyDir: {}  # Writable space for Tomcat
        - name: tomcat-dir
          emptyDir: {}  # Writable space for Tomcat
        - name: cron-output
          emptyDir: {}  # Writable space for cron job output
        - name: cronjobs
          emptyDir: {}  # Writable space for cron job scripts
